name: ci-javascript-samples

env:
  ROOT_FOLDER: BotBuilder-Samples/samples/javascript_nodejs/02.echo-bot

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "samples/**/*.js"
      - "samples/**/*.ts"

jobs:
  generate:
    name: detect and generate bot matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - name: git diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: samples/**/*.+(ts|js)
          ABSOLUTE: true

      - name: generate matrix
        id: set-matrix
        run: |
          MATRIX_JSON="[]"
          
          # Check if there are any differences
          if [[ -n "${{ env.GIT_DIFF_FILTERED }}" ]]; then
            MATRIX_JSON=$(echo "${{ env.GIT_DIFF_FILTERED }}" | jq -R -s 'split("\n") | map(select(length > 0)) | map({ name: ., folder: . })')
          fi
          
          echo "Generated Matrix: $MATRIX_JSON"
          echo "matrix=$MATRIX_JSON" >> $GITHUB_ENV

  build:
    needs: generate
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJSON(env.matrix) || fromJSON('[]') }}
      fail-fast: false

    name: bot - ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v3

      - name: use node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Check if package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found!"
            exit 1
          fi
        working-directory: ${{ matrix.folder }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.folder }}

      - name: Build project (if applicable)
        run: |
          if [ -f package.json ] && jq -e .scripts.build package.json > /dev/null; then
            npm run build
          fi
        working-directory: ${{ matrix.folder }}

      - name: Lint project
        run: |
          if [ -f package.json ] && jq -e .scripts.lint package.json > /dev/null; then
            npm run lint
          fi
        working-directory: ${{ matrix.folder }}
