name: ci-javascript-samples

env:
  ROOT_FOLDER: samples/javascript_nodejs/02.echo-bot

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "samples/javascript_nodejs/02.echo-bot/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Echo Bot
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          working-directory: ${{ env.ROOT_FOLDER }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.ROOT_FOLDER }}

      - name: Build project (if applicable)
        run: npm run build
        if: test -f package.json && jq -e .scripts.build package.json > /dev/null
        working-directory: ${{ env.ROOT_FOLDER }}

      - name: Run ESLint
        run: npx eslint .
        working-directory: ${{ env.ROOT_FOLDER }}

      - name: Run tests (if applicable)
        run: npm test
        if: test -f package.json && jq -e .scripts.test package.json > /dev/null
        working-directory: ${{ env.ROOT_FOLDER }}
