name: ci-javascript-samples

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-echo-bot:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo into a subfolder named 'repo'
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: repo

      # 2) List all files for debugging, to confirm folder structure
      - name: List repo files
        run: ls -R
        working-directory: repo

      # 3) Install dependencies inside the Echo Bot folder
      - name: Install dependencies
        run: npm install
        working-directory: repo/samples/javascript_nodejs/02.echo-bot

      # 4) Build the project (if a "build" script exists in package.json)
      - name: Build project
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build script found, skipping..."
          fi
        working-directory: repo/samples/javascript_nodejs/02.echo-bot

      # 5) Test the project (if a "test" script exists in package.json)
      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test || echo "No test script found, skipping..."
          fi
        working-directory: repo/samples/javascript_nodejs/02.echo-bot
