name: ci-javascript-samples

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-echo-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm installname: ci-javascript-samples

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build-echo-bot:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your repo into './repo'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo

      # 2️⃣ Confirm the folders
      - name: List all files
        run: ls -R
        working-directory: repo

      # 3️⃣ Install dependencies (update path to actual sample folder)
      - name: Install dependencies
        run: npm install
        working-directory: repo/samples/javascript_nodejs/02.echo-bot

      # 4️⃣ Build (optional)
      - name: Build project
        run: npm run build
        working-directory: repo/samples/javascript_nodejs/02.echo-bot

      # 5️⃣ Test (optional)
      - name: Test
        run: npm test
        working-directory: repo/samples/javascript_nodejs/02.echo-bot

        working-directory: BotBuilder-Samples/samples/javascript_nodejs/02.echo-bot

      - name: Build project
        # Only run this if you have a "build" script in package.json
        run: npm run build
        working-directory: BotBuilder-Samples/samples/javascript_nodejs/02.echo-bot

      - name: Run tests
        # Only run this if you have a "test" script in package.json
        run: npm test
        working-directory: BotBuilder-Samples/samples/javascript_nodejs/02.echo-bot
